### ISSUE TITLE
Browser hijack?

### ISSUE THREAD

**Issue by franciscop** [mthamil/Tab-Wheel-Scroll#15]
Hi, I am suffering browser hijack (try to visit one page and get redirected to another). I only have 3 add-ons installed, including Tab-Wheel-Scroll which I love, so just wanted to see if there's any way this is a problem with the add-on or it's with my network. Those three add-ons are:

- LastPass
- AdBlock Plus (tried with other ad-blocker and same things happen, so I guess not their problem)
- Tab-Wheel-Scroll

So just wanted to ask, has there been any change recently to the published version and how can I check/validate it? **Most likely option is my router/hotel is doing it** but I wanted to make sure this add-on is safe.

**Comment by mthamil-eml** [comment]
I'm pretty sure tab wheel scroll can't be responsible for this. It doesn't interact with the page url or contents at all. You can look through the code and releases for yourself if you want.

**Comment by franciscop** [comment]
I totally thought so, I was reading through the code before saying so but I was wondering about an after-released change (such as can someone else release a version besides you? is there any unclaimed access/key?). However, after using it full-day through a different network I didn't see any hijacking so I can safely assume it was my hotel. Thanks for the answer though!
