### ISSUE TITLE
Not working with Private Window

### ISSUE THREAD

**Issue by ElectricGestalt** [mthamil/Tab-Wheel-Scroll#18]
This is a great addon, but for some reason (I think after a recent Firefox update) it does not function if I start Firefox with a Private Window _unless_ I already have a normal window open. This issue is happening on Firefox 50.1.0 on Ubuntu. Also, opening a normal window afterwards does not resolve the problem until I close and reopen the private one.

**Comment by ghost** [comment]
I've been having the same problem using "never remember history" where Firefox only uses private windows. The scrolling won't work with the first/initial window that opens when Firefox starts so I need to open a new one and close the first.

Debugging it I found that Firefox just has a bug where it doesn't list the first private window in their window list. Found a bugzilla entry and luckily this will get fixed soon when Firefox 51 is released in a few weeks.
https://bugzilla.mozilla.org/show_bug.cgi?id=1224863

**Comment by ghost** [comment]
Firefox 51 is released and as expected tab wheel scrolling now works for me on the first private window too.

**Comment by mthamil** [comment]
Good to hear!
