### ISSUE TITLE
tab scrolling 

### ISSUE THREAD

**Issue by reelsense** [mthamil/Tab-Wheel-Scroll#20]
Tab-Wheel-Scroll use to have a 1:1 scroll wheel ratio.

eg:
One scroll wheel ratchet = one tab change.

Now it appears to use scroll acceleration, and you have to flick the scroll wheel fast and short and get lucky if you scroll one tab. Or scroll very slow for many ratchets before it switches just one tab. Most of the time it just zooms past the tab I want. 

FF 52
OS X 10.12.3

**Comment by mthamil** [comment]
Do you have a mouse with a wheel that just spins freely?  I don't appear to have this issue myself; one "ratchet" of the wheel moves one tab. I DO have a Logitech mouse with the microgear adjuster on the bottom, and if I put it into full free wheel mode it does this.

**Comment by reelsense** [comment]
I don't have a mouse wheel that spins freely. I don't use any special drivers for the Mouse.

I haven't been using Firefox much but wanted to give it a try again after the added e10s support in Tab-Wheel-Scroll. I just remember it being a 1:1 ratio when I used it the most in Ubuntu. Maybe FF uses the OS scroll settings so it's like this on OS X?

**Comment by reelsense** [comment]
Since your last update was 2017-01-05, it looks like FF54 resolved this issue.
