### ISSUE TITLE
Disabled on Firefox Nightly 57.0a1 (2017-09-20) (64-bit)

### ISSUE THREAD

**Issue by rkmax** [mthamil/Tab-Wheel-Scroll#22]

**Comment by mthamil** [comment]
Yes, and unfortunately it will stay that way. There is currently no way forward for this extension.

**Comment by rkmax** [comment]
Oh that is very bad news

**Comment by mthamil** [comment]
Yes, and I am sorry about it. If you were so inclined, you could post in this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1246706 to express your disapproval. Unfortunately, Mozilla is unlikely to listen.

**Comment by rkmax** [comment]
thanks for the info @mthamil but yeah is seems like it'll not to happen. the solution of Stephan Sokolow it seems is not a craziness 🤣 


> Firefox's default behaviour is a serious UX wart on Linux desktops, where all major widget toolkits (as well as Chrome/Chromium) map "scroll wheel on a tab bar" to "change tab focus".
> 
> (In fact, it's a serious enough break from my muscle memory that, as a backup plan, I've started speccing out a utility which functions sort of like a keylogger under the hood, but instead hijacks scroll events on the top 37px of any window with WM_CLASS = ("Navigator", "Firefox") and replaces them with synthesized Ctrl[+Shift]+Tab X11 events.)
