### ISSUE TITLE
Add support for Firefox >= 57

### ISSUE THREAD

**Issue by nini** [mthamil/Tab-Wheel-Scroll#23]
Currently, extension marked as "legacy", is it possible to bring it back?
Firefox Nightly 59

**Comment by mthamil** [comment]
Unfortunately, no. Mozilla has decided not to add comparable replacement APIs for WebExtensions.

**Comment by nini** [comment]
Sorry, but I think I forgot to thank you for this plugin and for your efforts working on that. Thanks :+1:

**Comment by mthamil** [comment]
I appreciate it, but unfortunately, it is simply not possible to support Firefox 57 or greater. Mozilla has refused to add the necessary replacement APIs for Web Extensions as seen here<https://bugzilla.mozilla.org/show_bug.cgi?id=1246706>. I did try; I even joined a phone conference with them. They say UI modifications are not in scope of Web Extensions

On Nov 23, 2017 1:19 AM, nini <notifications@github.com> wrote:

Sorry, but I think I forgot to thank you for this plugin and for your efforts working on that. Thanks 👍
