### ISSUE TITLE
Not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by senorsmile** [mthamil/Tab-Wheel-Scroll#25]
On Firefox 57, we get this message when trying to install: 

> Not compatible with Firefox Quantum

**Comment by mthamil** [comment]
That is correct. Unfortunately, it is simply not possible to support Firefox 57 or greater. See #19.

**Comment by senorsmile** [comment]
Ah sorry.  I didn't realize that was related when scanning the existing open issues.
