### ISSUE TITLE
Stopped working with Firefox 48

### ISSUE THREAD

**Issue by tom-rice** [mthamil/Tab-Wheel-Scroll#4]
Hi I upgraded Firefox Developer Edition from 47 to 48 this morning and my tab wheel scroll stopped working :( any chance you can test it out with this version and see what's up?
I am not using multi process mode by the way, if that makes any difference.

**Comment by dgutov** [comment]
Same here.

I'm using E10s, so it probably doesn't matter one way or another.

**Comment by dogancelik** [comment]
e10s is disabled, yeah new update breaks the add-on.

**Comment by mthamil** [comment]
I will have to look into it. I am using some of the "low-level" APIs because there aren't any high level that get me access to the tab container, so maybe that's the issue.

**Comment by mthamil** [comment]
For the time being, I have changed the upper limit compatibility on addons.mozilla.org to 47.* (sorry). After reviewing some documentation, I am pretty sure the use of low-level sdk apis is the cause of the breakage.

**Comment by jreybert** [comment]
All tab wheel addon seem broken (see also https://github.com/gomita/firegestures/issues/127 )

Seems related to  https://bugzilla.mozilla.org/show_bug.cgi?id=1263975

**Comment by jingyu9575** [comment]
Setting useCapture fixed it on my Firefox Dev 48.0a2

    tabContainer.addEventListener("wheel", this.wheelHandler, true);

    tabContainer.removeEventListener("wheel", this.wheelHandler, false);

**Comment by mthamil** [comment]
In that case I have a fix coming up pretty soon. I also discovered the useCapture issue while investigating that it stopped working in Thunderbird 48.  Someone else tipped me off in an email.

**Comment by mthamil** [comment]
Fixed by #5. A release is under review at the add-ons site.
